### ISSUE TITLE
Multiple ToF Sensors

### ISSUE THREAD

**Issue by Kokuko3** [BoffinFactory/PianoStaircase#22]
The current ToF sensors we are using are the [VL53L0x from Adafruit](https://www.adafruit.com/product/3317).

Currently we have been able to use the `VL53L0x_dual` example code to read in sensors tied together. But currently we do not have a working way to track more than 2.

We believe it to be possible as the `VL53L0x_multi` example seems to do this, but I am currently in the process of trying to understand how this code operates.

Please comment below or @Kokuko3 if you have any suggestions or have a working prototype for this step in the process!

**Comment by mkijowski** [comment]
I2C limits seem high enough, theoretically can run 128 I2C devices: https://forum.arduino.cc/t/how-many-devices-can-you-connect-to-i2c/156120

**Comment by mkijowski** [comment]
More data:
The VL53L0x I2C address is controlled via software, so it needs set each reboot of the arduino, requiring setup time and additional code / software complexity.  We are currently stuck at 2 Time of Flight I2C devices at once (working), when we move to three we start getting errors both due to size of the program / memory usage AND errors actually getting data out of all three ToF sensors (all three just read 0).

One potential solution would be to get an I2C multiplexer device that would allow for multiple devices to operate concurrently with the same I2C address.  Thoughts on this (multiplexer versus straight hookup and software addressing of Time of Flight devices)?

**Comment by mkijowski** [comment]
closed with #28
